defaults:
  - hyp: sudoku_default
  - model: transformer

name: sudoku
train_data: expert
test_data: extreme

max_train_samples: 50000
max_test_samples: 10000

model:
  in_channels: 10
  out_channels: 10
  spatial_dims: 2
